### ISSUE TITLE
Surrogates: Error Uploading ALAMO surrogate model

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#275] opened 2018-09-10 16:54 UTC
- I used the "Surrogates" tab to create an ALAMO surrogate model for an Aspen Plus simulation
- The .py files are uploaded to my working directory
- However, when I tried to use the ALAMO model as a "Plug In" in "Flowsheet", it is not included in the list of plug-ins
- @eslickj and I opened the .py file using Notepad++
- We found that for some of the input variables, if the description ("vdesc") runs for 2 lines, the 2nd line becomes a line of code instead of a string of texts
- Once we fixed these lines of code, we no longer have the issue
- But can we do something to prevent the part of the variable's description from being a line of code?

**Comment by eslickj** [comment] 2019-03-08 17:50
@fsoepyan, can you remeber the details of this?  I guess is was somehow a malformed description string, and I could probably catch that, but I can't recall how this happened.  I you don't remember and can't reproduce it let's close this and open a new issue if it happens again.  If you can reproduce it, send me an example.

**Comment by fsoepyan** [comment] 2019-03-08 19:02
@eslickj: I remember that there was one time I tried to generate an ALAMO surrogate model, and the description for one of the variables ran for two lines, and Python thought that the second line is a code instead of a comment.

I will try to reproduce this error.

**Comment by eslickj** [comment] 2019-05-22 19:29
I probably fixed this by replacing "\n" with " " in variable descriptions when writing the plugin.

**Closed by eslickj** 2019-05-22 19:29 UTC
Labels: Surrogates, bug :bomb:
