### ISSUE TITLE
SDoE Version 2 documentation 

### ISSUE THREAD

**Issue by candcook** [CCSI-Toolset/FOQUS#651] opened 2019-12-05 18:27 UTC
Update documentation to include new functionality of NonUniform Space Filling in SDoE.

**Comment by ksbeattie** [comment] 2019-12-10 20:42
related to #638

**Comment by sotorrio1** [comment] 2019-12-13 18:33
This is a duplicate of #653. Closing the issue

**Closed by sotorrio1** 2019-12-13 18:33 UTC
Labels: Priority:High
