### ISSUE TITLE
Issue using non-uniform space filling option

### ISSUE THREAD

**Issue by Daison2102** [CCSI-Toolset/FOQUS#830] opened 2020-10-07 20:39 UTC
Issues when reproducing Examples NUSF-1 and NUSF-2 in the Sequential Design of Experiments.

Not able to run these examples in FOQUS 3.6.0, as FOQUS seems to freeze when I clicked on the Test SDOE button to estimate the time taken for creating the designs (see the attached image). In the terminal only appears Random star 0 after waiting more than two hours.
In FOQUS 3.5.1 any issue found using the non-uniform space filling option, the elapsed time after clicking Test SDOE button was only 88 s

-  **In FOQUS 3.6.0**

![Issue using non-uniform space filling option foqus 3 6 0](https://user-images.githubusercontent.com/32642037/95385093-83ea2980-08bb-11eb-960c-e398a3ddbcc0.png)

-  **In FOQUS 3.5.1**

![Issue using non-uniform space filling option foqus 3 5 1](https://user-images.githubusercontent.com/32642037/95385109-89477400-08bb-11eb-8dd9-d835831e93f3.png)

**Comment by sotorrio1** [comment] 2020-10-08 03:09
This is a known issue reported in issue #766 and we're currently taking care of it. Stay tuned! :)

**Comment by ksbeattie** [comment] 2020-10-13 19:55
Closing as a duplicate of #766

**Closed by ksbeattie** 2020-10-13 19:55 UTC
Labels: SDOE
