### ISSUE TITLE
Stage 1 space filling design

### ISSUE THREAD

**Issue by atowfiq** [CCSI-Toolset/FOQUS#231] opened 2018-06-19 20:26 UTC
LANL is developing code for space filling design based on a user-supplied candidate set. R code developed by Christine is being translated into python by Towfiq.

Preliminary non-GUI code should be completed sometime in July. Then some testing by the team would be beneficial.

**Comment by ksbeattie** [comment] 2018-07-17 20:02
Is this related or a duplicate of #245?

**Comment by ngbrenda** [comment] 2018-07-25 18:07
Yes, this is a duplicate.

**Closed by ngbrenda** 2018-07-25 18:07 UTC
