### ISSUE TITLE
Aspen SLM 12.0

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#887] opened 2021-03-03 00:24 UTC
# Description
In order to use Aspen v12.0 need to update SLM license servers to 12.0.  Update the three license servers starting with dudley.

- [X] dudley 03/01/2021
- [ ] xena
- [ ] AWS

**Comment by ksbeattie** [comment] 2021-04-06 20:21
duplicate of #890

**Closed by ksbeattie** 2021-04-06 20:21 UTC
Labels: Priority:High
