### ISSUE TITLE
Turbine Upload Error

### ISSUE THREAD

**Issue by johnbaca** [CCSI-Toolset/FOQUS#381] opened 2019-02-11 16:02 UTC
With help of @CSRussell2319 we attempted to upload an Aspen APW file with it's accompanying ".opt" and ".dll" files and received the error message below. This occurred using the latest version of FOQUS, Turbine, and Turbine Client. TurbineWebAPIService was running and we tried restarting the service, but it didn't help.

![error_turbine](https://user-images.githubusercontent.com/47044799/52574620-f00c4580-2dd9-11e9-9fd8-bb8799933405.JPG)

**Comment by CSRussell2319** [comment] 2019-02-11 16:32
Also, @boverhof maybe should consider removing local directory paths in the error messages (there are a few C:\Users\boverhof references).

**Comment by jmorgan29** [comment] 2019-02-11 19:22
@johnbaca, Just to confirm, you were able to upload the json/apw files to the Turbine and run the node, getting the 'Simulation completed with an error 1, Failure in node calculation...'. When you went back and added in the opt and dll files, you were then unable to add the model to the Turbine?

**Comment by johnbaca** [comment] 2019-02-11 19:54
@jmorgan29 yes once I included the dll and opt files to turbine, this error message popped up. When I did not include the two files, every trial i ran through the node, was producing a 'Simulation completed with an error 1'.

**Comment by jmorgan29** [comment] 2019-02-11 21:51
@johnbaca, the reason for the 'error 1' is due to the Fortran subroutines contained in the dll file not being available when Turbine runs the model, causing the Aspen simulation to fail. I tried uploading the files to Turbine again using both of the methods that I mentioned in my previous e-mail and found the following:

-When adding the opt/dll files in SimSinter configuration file and then selecting this file in 'Add/Update Turbine Model' I get the same error message that you have reported here. I have found this method to work for other examples, but for some unknown reason it does not work for this particular example.

-When I do not add the opt/dll files to the configuration file, but select them using the 'Add Files' button under  'Add/Update Turbine Model', the model is successfully added to Turbine. I would recommend attempting this method if you have not done so already.

**Comment by johnbaca** [comment] 2019-02-11 23:50
@jmorgan I just tired loading the dll/opt files using the select 'add files' button and got the exact error window.

**Comment by jmorgan29** [comment] 2019-02-12 15:12
@johnbaca, I have one additional suggestion. I noticed that when I got the 'Gateway unknown http error' when trying to add in the 'Gen2_Model' to the Turbine, that another version of this model already existed in Turbine. When I deleted it and re-uploaded, it worked correctly and the node was able to run. In your case, I think the version that you uploaded (without dll/opt) still exists in the Turbine, and that is the reason you cannot upload it again. If you delete the old version and add it again with the dll/opt, I think/hope that you will be able to upload it and run the model in a node.

**Comment by CSRussell2319** [comment] 2019-02-12 15:40
@jmorgan29, that may explain why we've had success in the past after reinstalling turbine. Simulations are purged when turbine is reinstalled.

**Comment by jmorgan29** [comment] 2019-02-12 18:17
@CSRussell2319, that does seem to be true.

**Comment by eslickj** [comment] 2019-02-13 16:30
@boverhof, I'm pretty sure you used to be able to update and existing simulation.  Updating an existing simulation calls a different command.  Maybe something changed and I'm calling it wrong, or there is a Python 3 conversion bug somewhere.  Here is the offending code if anything looks off.  I think the getFile() is the turbine config file.

``` python
        # Upload the sinter configuration file
        args = ["-r", "configuration", name, sinterConfigPath, self.getFile()]
        try:
            turbine.commands.turbine_simulation_script.main_update(args)
        except Exception as e:
            raise TurbineInterfaceEx(
                code = 0,
                msg = "Could not upload sinter configuration file",
                e = e,
                tb = traceback.format_exc())
        # upload model file
```

**Comment by ksbeattie** [comment] 2019-04-09 19:49
@boverhof, needs to take another look at this to see if this issue still exists or was introduced earlier.

**Comment by ksbeattie** [comment] 2019-04-16 20:10
@boverhof will work on this after updating his cloud based work.

**Comment by ksbeattie** [comment] 2019-04-16 20:12
@fsoepyan will try and reproduce this as well.

**Comment by fsoepyan** [comment] 2019-04-17 16:02
In response to the comments from @eslickj (from Feb. 13):
- I am currently using FOQUS for a project
- Whenever I need to update an Aspen or Excel model, I would first open the SimSinter json file (with the original name)
- Then, I would make sure that the new Aspen or Excel model (that opens automatically) is the new one
- I would then click the "Finish" button in SimSinter to save and close the json file
- I would go to the "Add/Update Model to Turbine" menu in FOQUS
- From the dropdown list, I would delete the old model
- Then, I would upload the model (with the same name as the previous one) into Turbine
- I managed to upload and run the updated models successfully in FOQUS

Question:
Does that mean we can close this issue?

**Comment by johnbaca** [comment] 2019-04-17 16:15
@fsoepyan these steps help out a lot and I have been doing a similar procedure when working with Foqus. I think this issue has been resolved on my end, Thank you.

**Comment by CSRussell2319** [comment] 2019-04-17 16:25
I would argue that having an add/update button implies that an update feature exists. If this is how we "update" a model I think the phrasing should be changed and better instructions should be provided to the user.

**Comment by fsoepyan** [comment] 2019-04-23 16:19
- If we need to update the documentation, the instructions should be added to the docs\source\chapt_flowsheet\reference\home.rst file
- Because the old pictures of the FOQUS toolbar/icons are in this section, updating this section of the manual should wait until after we merge PR #474

**Comment by ksbeattie** [comment] 2019-04-23 20:07
@eslickj points out that the update should work without having to delete first.  @fsoepyan will test this.  @boverhof will look at what it will take to make sure the update works without a delete.

**Comment by fsoepyan** [comment] 2019-04-24 18:09
- I updated a model in Turbine without deleting the old file that's already in Turbine, and it works.
- I managed to successfully upload and run the model in FOQUS.

**Comment by boverhof** [comment] 2019-04-24 21:46
From the original description I can't tell what the exact original scenario was.   

I tested the most basic scenario:  Upload the "sinter" configuration to TurbineLite ( FIPS compliant release ) and the py3 turb_client from GIT.  The test works.

## Zero Simulations
```
(base) C:\Users\Administrator\Desktop\test>more turbine.cfg
[Simulation]
url=http://localhost:8000/TurbineLite/Simulation
[Authentication]
username=
password=

#[Logging]
#fileConfig=logging.conf

(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_list -v turbine.cfg
Total Simulations: 0
```
## Create Simulation test1
```
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_create test1 ACM turbine.cfg

(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_list -v turbine.cfg
Total Simulations: 1
============================================================
============================================================
       test1
         Application:          ACM
                  Id: f8b6ef5e-c55b-49e4-a51d-1a2d56852504
                Name:        test1
        StagedInputs: [{'Id': '4bb6cded-518e-4fe6-99ef-b2a0002a112f', 'MD5Sum': '', 'Name': 'aspenfile'}, {'Id': 'c34531
41-815b-4b6e-8d1e-a505834fb59e', 'MD5Sum': '', 'Name': 'configuration'}]
```
## Add First Configuration File Version
```
(base) C:\Users\Administrator\Desktop\test>more simulation_test1_configuration.txt
DUMMY CONFIG 1

(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_update -r configuration test1 simulation_test1_configuration.txt turbine.cfg

(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_list -v turbine.cfg
Total Simulations: 2
============================================================
============================================================
       test1
         Application:          ACM
                  Id: f8b6ef5e-c55b-49e4-a51d-1a2d56852504
                Name:        test1
        StagedInputs: [{'Id': '4bb6cded-518e-4fe6-99ef-b2a0002a112f', 'MD5Sum': '', 'Name': 'aspenfile'}, {'Id': 'c34531
41-815b-4b6e-8d1e-a505834fb59e', 'MD5Sum': '', 'Name': 'configuration'}]
============================================================
============================================================
       test1
         Application:          ACM
                  Id: 57652387-8256-4e63-bc37-a0b35dbac61d
                Name:        test1
        StagedInputs: [{'Id': '34362fee-5761-40de-866e-2a735db8418e', 'MD5Sum': '53B802085541CA2DEF80D7FCE5C932634AFD9AD
A', 'Name': 'configuration'}, {'Id': 'a6ec95ce-7b6f-4655-9415-282f332a8f49', 'MD5Sum': '', 'Name': 'aspenfile'}]
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_get -r configuration
 test1 turbine.cfg
DUMMY CONFIG 1
```
## Update to Second Configuration Version
```
(base) C:\Users\Administrator\Desktop\test>more simulation_test1_configuration_X.txt
DUMMY CONFIG 2
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_update -r configuration test1 simulation_test1_configuration_X.txt turbine.cfg

(base) C:\Users\Administrator\Desktop\test>
(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_list -v turbine.cfg
Total Simulations: 3
============================================================
============================================================
       test1
         Application:          ACM
                  Id: f8b6ef5e-c55b-49e4-a51d-1a2d56852504
                Name:        test1
        StagedInputs: [{'Id': '4bb6cded-518e-4fe6-99ef-b2a0002a112f', 'MD5Sum': '', 'Name': 'aspenfile'}, {'Id': 'c34531
41-815b-4b6e-8d1e-a505834fb59e', 'MD5Sum': '', 'Name': 'configuration'}]
============================================================
============================================================
       test1
         Application:          ACM
                  Id: 57652387-8256-4e63-bc37-a0b35dbac61d
                Name:        test1
        StagedInputs: [{'Id': '34362fee-5761-40de-866e-2a735db8418e', 'MD5Sum': '53B802085541CA2DEF80D7FCE5C932634AFD9AD
A', 'Name': 'configuration'}, {'Id': 'a6ec95ce-7b6f-4655-9415-282f332a8f49', 'MD5Sum': '', 'Name': 'aspenfile'}]
============================================================
============================================================
       test1
         Application:          ACM
                  Id: 60038164-b8c5-41c3-bc50-e6a21a69a6cc
                Name:        test1
        StagedInputs: [{'Id': '996b2c7f-2291-47b0-ad88-d27a15cf5805', 'MD5Sum': '', 'Name': 'aspenfile'}, {'Id': 'e1ba78
f8-29d4-4ebc-a57a-45973609466b', 'MD5Sum': '40C446C691ABB396D2F9DDE6246CC5A5E7C4E0EC', 'Name': 'configuration'}]

(base) C:\Users\Administrator\Desktop\test>python \ProgramData\Anaconda3\Scripts\turbine_simulation_get -r configuration
 test1 turbine.cfg
DUMMY CONFIG 2
(base) C:\Users\Administrator\Desktop\test>
```

**Comment by ksbeattie** [comment] 2019-04-30 19:49
@johnbaca and/or @CSRussell2319 could one of you confirm that this has been fixed?

**Comment by johnbaca** [comment] 2019-05-03 14:32
@ksbeattie yes this has been fixed. I am able to upload a file without deleting the file first.

**Comment by boverhof** [comment] 2019-05-07 17:41
This is done.

**Closed by boverhof** 2019-05-07 17:41 UTC
Labels: Turbine, bug :bomb:
