### ISSUE TITLE
Intermittent failures in TestOUU.testRunOUU on macOS ARM

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1195] opened 2024-02-27 23:24 UTC
```log
---------------------------- Captured stdout setup -----------------------------
0
1
2
3
4
5
6
7
8
9
10
11
   variable 1 Y

**********************************************************************
*      Welcome to PSUADE (version 1.10.0)
**********************************************************************
PSUADE - A Problem Solving environment for 
         Uncertainty Analysis and Design Exploration (1.10.0)
(for help, enter <help>)
======================================================================
psuade> readApplication WARNING: opt driver PSUADE_LOCAL not found.
**********************************************************************
PSUADE : Search for local minima in sample space.
         number of samples = 1
	 optimization starting point 1 : 
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
		   0.00000000e+00
				 Y =   1.00000000e+35
**********************************************************************
**********************************************************************
PSUADE OPTIMIZATION 1 (1) : 
	 starting X(     1) =   0.00000000e+00
	 starting X(     2) =   0.00000000e+00
	 starting X(     3) =   0.00000000e+00
	 starting X(     4) =   0.00000000e+00
	 starting X(     5) =   0.00000000e+00
	 starting X(     6) =   0.00000000e+00
	 starting X(     7) =   0.00000000e+00
	 starting X(     8) =   0.00000000e+00
	 starting X(     9) =   0.00000000e+00
	 starting X(    10) =   0.00000000e+00
	 starting X(    11) =   0.00000000e+00
	 starting X(    12) =   0.00000000e+00
	 starting Y =   1.00000000e+35
**********************************************************************
**********************************************************************
*     1- OR 2-STAGE OPTIMIZATION UNDER UNCERTAINTY (OUU)
======================================================================
This optimization capability solves the following problem:

   minimize_Z1 { Phi_{Z3,Z4} [ G(Z1,Z2,Z3,Z4) ] } 

   subject to either:
    (a) bound constraints on Z1, Z2, and Z4 (use bobyqa); or 
    (b) no constraint on Z1, Z2, and Z4 (use newuoa); or
    (c) inequality constraints on Z1,Z2,Z3,Z4 (use cobyla)
    as the level-1 optimizer.)

   Z3 is a set of discrete parameters for which a sample

   is to be provided by the user. 

   (0) How to perform regular optimization? 
       In this case 
       - Z1 will be the optimization variables
       - Z2 should be an empty set
       - Z3 should be an empty set
       - Z4 should be an empty set
       - G(Z1,Z3,Z4)=G(Z1) is the simulator (opt_driver)
   (1) How to perform 1-level OUU? 
       In this case 
       - Z1: the optimization variables
       - Z2: should be an empty set
       - Z3: parameters that you will provide a sample.
       - Z4: parameters that you do not provide a sample.
         (optionally, you can choose sampling scheme and
          whether you want response surface for Z4).
       - G(Z1,Z3,Z4) is the simulator (opt_driver)

   (2) How to perform 2-level OUU? 
       In this case 
       - Z1: the optimization variables
       - Z2: the set of level-2 optimization parameters.
         If Z2 do not need to be published outside of the G
         function, then it can be specified as an empty set.
       - Z3: parameters that you will provide a sample for.
       - Z4: parameters that you do not provide a sample.
       - There are 2 options to how to set up G(Z1,Z2,Z3,Z4):
         (a) A user-provided level 2 optimizer that does

              G(Z1,Z2,Z3,Z4) = minimize_Z2{F(Z1,Z2,Z3,Z4)}

             where F(Z1,Z2,Z3,Z4) is embedded in G(Z1,...)

             In this case, the user will provide G(Z1,...)
             via opt_driver (i.e. opt_driver = gfunction)
         (b) A user-provided function F(Z1,...) such that

              G(Z1,Z2,Z3,Z4) = minimize_Z2 {F(Z1,Z2,Z3,Z4)}

             In this case, user is expected to provide the
             F(Z1,...) function via 'opt_driver = ffunction'
             and OUU provides the optimizer (BOBYQA).

   In case 1 and 2, Phi_{Z3,Z4} is a functional on G(Z1,...)
   with respect to Z3 and Z4, e.g. Phi_{Z3,Z4} may be:
   1. mean of G(Z1,Z2,Z3,Z4) with respect to Z3,Z4 (default)
   2. mean of G(Z1,Z2,Z3,Z4) + alpha * std dev of G(Z1,...)
   3. G(Z1,Z2,Z3*,Z4*) such that 
         Prob(G(Z1,Z2,Z3,Z4)>G(Z1,Z2,Z3*,Z4*)) = epsilon
   4. min_{Z3,Z4} G(Z1,Z2,Z3,Z4) given Z1,Z2 (robust opt.)
======================================================================
In the above formulation, the total no. of parameters M = 12
These parameters are to be divided into four groups:
(1) Stage 1 optimization parameters Z1 (M1 >= 1) 
(2) Stage 2 optimization (recourse) parameters Z2
(3) uncertain parameters Z3 (with a user-provided sample) 
(4) uncertain parameters Z4 
    - continuous parameters (PSUADE to generate sample), or
    - a large sample (created by PSUADE from RS) 
Thus, the first M1+M2 parameters are considered to be
optimization parameters, and M3+M4 are uncertain parameters
so that M = M1 + M2 + M3 + M4.
======================================================================
To reuse simulation results (e.g. from before abrupt
termination), turn on save_history and use_history
optimization options in the ANALYSIS section (e.g.
optimization save_history). You will see a text file
called 'psuade_ouu_history' afterward.
**********************************************************************
IF YOU ARE READY TO MOVE ON, ENTER 'y' AND RETURN : ======================================================================
M1 = number of design (level 1 optim.) parameters
Enter M1 (between 1 and 12) : M2 = no. of recourse (level 2 optim.) parameters
Enter M2 (between 0 and 8) : M3 = number of discrete (scenario) parameters
Enter M3 (between 0 and 4) : In the following, please select type for each variable:
  1. design variable (level 1 optimization parameter)
  2. operating variable (level 2 optimization parameter)
  3. discrete uncertain variable (a sample will be given)
  4. continuous uncertain variable
NOTE: make sure your specification matches with above.
Type for variable 1 ? Type for variable 2 ? Type for variable 3 ? Type for variable 4 ? Type for variable 5 ? Type for variable 6 ? Type for variable 7 ? Type for variable 8 ? Type for variable 9 ? Type for variable 10 ? Type for variable 11 ? Type for variable 12 ? ======================================================================
Input    1 is a design parameter.
Input    2 is a design parameter.
Input    3 is a design parameter.
Input    4 is a design parameter.
Input    5 is an operating parameter.
Input    6 is an operating parameter.
Input    7 is an operating parameter.
Input    8 is an operating parameter.
Input    9 is a discrete uncertain parameter.
Input   10 is a discrete uncertain parameter.
Input   11 is a discrete uncertain parameter.
Input   12 is a discrete uncertain parameter.
======================================================================
OUUOptimizer: setting optimization simulation driver.
              driver = PSUADE_LOCAL
======================================================================
Select which functional Phi_{Z3,Z4} to use: 
  1. mean of G(Z1,...) with respect to Z3,Z4 (default)
  2. mean of G(Z1,...) + beta * std dev of G(Z1,...)
  3. G(Z1,Z2,Z3*,Z4*) such that 
         Prob(G(Z1,...)>G(Z1,Z2,Z3*,Z4*)) = 1 - alpha
     This is also called value-at-risk with confidence
     level alpha.
Enter your choice of functional (1, 2 or 3) : ======================================================================
A sample for Z3 is needed from you. Data format is:
line 1: <nSamples> <nInputs> 
line 2: <sample 1 input 1> <input 2> ... <probability>
line 3: <sample 2 input 1> <input 2> ... <probability>
...
Enter user sample file name : User sample for Z3 has 200 points
User sample for Z3 CDF = 0.000000e+00 (should be ~1)
For 2-stage OUU, you have 2 options for inner optimization:
(1) You can use BOBYQA available in PSUADE (in this case
    opt_driver should point to your original function), or
(2) You can provide your own optimizer (in opt_driver), or
    it is one-level optimization.
NOTE: Most likely you will choose (2) or answer y below.
Use your own optimizer instead of BOBYQA? (y or n) NOTE: Make sure your optimizer executable has been
      assigned to 'opt_driver' and it optimizes with
      respect to the 5-th to 8-th parameters.
======================================================================
Each simulation calls the opt_driver with 1 sample point.
For higher efficiency (less I/O), you have the option to
provide in 'ensemble_opt_driver' an executable that can
run multiple sample points. In this case, OUU calls the
ensemble executable with the following sequence: 
    <ensemble_opt_driver> <sampleFile> <outputFile>

where <sampleFile> is in the following format:
   line 1: <nSamples>
   line 2: Sample point 1 input values
   line 3: Sample point 2 input values
   line n: ...

and <outputFile> should have all sample output values.

Use ensemble opt driver for ensemble runs ? (y or n) ======================================================================
You can configure OUU to run the ensemble simulations in
parallel/asynchronous using the Linux fork/join. If 'n'
is entered below, the opt_driver simulator will be
evaluated sequentially (one sample point at a time).
If 'y' is selected instead, be careful, because PSUADE
PSUADE will launch 200 jobs simultaneously, which may
jam up the job queuing system.
Turn on asynchronous mode ? (y or n) ======================================================================
**********************************************************************
*** Optimization Under Uncertainty begins
----------------------------------------------------------------------
 ** OUUOptimizer summary of optimization parameters: 
  * Number of first  stage optimization parameters = 4
  * Number of second stage optimization parameters = 4
  * Number of discrete   uncertain parameters      = 4
  * Number of continuous uncertain parameters      = 0
----------------------------------------------------------------------
 ** max fevals = 1000000
 ** tolerance  = 1.000000e-06
----------------------------------------------------------------------
 ** Optimizer = bobyqa (bound-constrained)
----------------------------------------------------------------------
OUUOptimizer initial X   1 = 0.000000e+00
OUUOptimizer initial X   2 = 0.000000e+00
OUUOptimizer initial X   3 = 0.000000e+00
OUUOptimizer initial X   4 = 0.000000e+00
======================================================================
OUUOptimizer: calling bobyqa
OUUOptimizer: Outer optimization iteration = 1
OUUOptimizer: Outer optimization loop FuncEval 1.
    Current Level 1 input   1 = 0.000000e+00
    Current Level 1 input   2 = 0.000000e+00
    Current Level 1 input   3 = 0.000000e+00
    Current Level 1 input   4 = 0.000000e+00
WARNING: there are 200 failed runs out of 200
ERROR: X3 sample cannot admit failures ==> terminate.



_DialogProxy(window_title='', text='OUU: Optimization error.\nPlease consult the FOQUS UQ developers for assistance.')
```

**Comment by ksbeattie** [comment] 2024-03-26 20:30
This came from following [OUU tutorial #1](https://foqus.readthedocs.io/en/stable/chapt_ouu/tutorial.html#example-1-ouu-with-discrete-uncertain-parameters-only).

**Comment by lbianchi-lbl** [comment] 2024-04-30 20:18
To reproduce locally:

```
conda create --yes --name test-foqus-1195 -c conda-forge -c CCSI-Toolset python=3.10 psuade-lite=1.9 && conda activate test-foqus-1195
pip install -r requirements-dev.txt
# run GUI tests for OUU; repeat this command multiple times since issue is intermittent
pytest --pyargs foqus_lib -x -v -m "gui" --qtbot-slowdown-wait-ms=100 --basetemp /tmp/foqus-1195 -k TestOUU
```

More information on running GUI tests available at https://github.com/CCSI-Toolset/FOQUS/wiki/howto-gui-tests

**Comment by ksbeattie** [comment] 2024-04-30 21:21
> To reproduce locally:
> 
> ```
> conda create --yes --name test-foqus-1195 -c conda-forge -c CCSI-Toolset python=3.10 psuade-lite=1.9 && conda activate test-foqus-1195
> pip install -r requirements-dev.txt
> # run GUI tests for OUU; repeat this command multiple times since issue is intermittent
> pytest --pyargs foqus_lib -x -v -m "gui" --qtbot-slowdown-wait-ms=100 --basetemp /tmp/foqus-1195 -k TestOUU
> ```
> 
> More information on running GUI tests available at https://github.com/CCSI-Toolset/FOQUS/wiki/howto-gui-tests

Run this about a dozen times on my new Apple M3 Max laptop and gotten XPASS every time....

**Comment by lbianchi-lbl** [comment] 2024-05-11 01:51
I believe one of the CI runs in #1221 gave us a way to compare two similar environments with different outcomes:

- :x: macOS (Apple Silicon), Python 3.11, [link to FOQUS working dir](https://github.com/CCSI-Toolset/FOQUS/actions/runs/9025014287/artifacts/1489531888)
- :heavy_check_mark: macOS (Apple Silicon), Python 3.12, [link to FOQUS working dir](https://github.com/CCSI-Toolset/FOQUS/actions/runs/9025014287/artifacts/1489548212)

@sotorrio1, if you click on those links, you should be able to download ZIP archives of the FOQUS working dir for the two cases. I tried to take a look but I couldn't see any obvious differences in the OUU files:

- `ouuTemp.dat` seems to be identical
- `ouu.out` is identical up to the reported failure:

  ![image](https://github.com/CCSI-Toolset/FOQUS/assets/48035537/9424519c-7a18-47c3-bba4-2095dd2ae81c)

**Comment by ksbeattie** [comment] 2024-06-04 19:55
Closing this as we can't reproduce this locally

**Closed by ksbeattie** 2024-06-04 19:55 UTC
Labels: OUU, PSUADE, Priority:Normal
