### ISSUE TITLE
Turbine: The button to test the remote configuration file is not working

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#28] opened 2017-10-02 20:11 UTC
From JIRA:
- Reporter: Miguel Zamarripa (@MAZamarripa)
- Assignee: John Eslick (@eslickj)
- Original title: Turbine - Remote connection. The button to test the remote configuration file is not working
- Created: 11/Aug/16 9:03 AM
- Updated: 11/Aug/16 9:03 AM

Description:

The button to test the remote configuration file is not working, this button is located in the Turbine Configuration window (create/edit window). 

Note that the button in the Turbine Getaway works.

Attachments:

![remote_turbine_testbutton](https://user-images.githubusercontent.com/30811140/31097149-4f637ea2-a78c-11e7-8f60-6e6f0d03a755.png)

**Comment by ksbeattie** [comment] 2018-05-15 20:13
@eslickj will need to have @boverhof make more progress on the AWS work to test this again.

**Comment by ksbeattie** [comment] 2018-07-10 19:58
@boverhof and @eslickj are working on this

**Comment by boverhof** [comment] 2018-07-17 20:31
@MAZamarripa please reproduce the issue and document the "steps".

I suspect this is a configuration/usability issue that I'd like to address.

**Comment by MAZamarripa** [comment] 2018-07-25 20:48
The test button now is working. It runs the test and I get an error, since the ".cfg" file is too old, so I suspect that the server is no longer available. You can close the issue @boverhof 
When I reported the issue, the button wasn't working at all.
![image](https://user-images.githubusercontent.com/24570008/43226554-32d194ae-902a-11e8-96ad-8a7836215c6f.png)

**Closed** 2018-07-25 21:09 UTC
Labels: Turbine, bug
