### ISSUE TITLE
OUU: Different solution generated using OUU tab vs. performing OUU using Optimization tab

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#269] opened 2018-08-23 13:32 UTC
- I have an example Aspen Plus file that I use for Optimization and OUU
- I have 3 decision variables and 2 uncertain (UQ) variables
- I ran this problem using the OUU tab, where I am using 25 sample points
- The solution I got was:

Objective value: -1041
Decision variable 1: 0.95
Decision variable 2: 301
Decision variable 3: 199

- Then I ran this problem using the Optimization tab, where I use the "Samples" tab to represent the different realizations of the uncertain variables (I'm still using 25 sample points)
- The solution I got was:

Objective value: -2269
Decision variable 1: 0.95
Decision variable 2: 315
Decision variable 3: 300

**Comment by sotorrio1** [comment] 2018-08-23 18:19
@fsoepyan could you send the problem you're using and the steps you're following? Thanks!

**Comment by sotorrio1** [comment] 2018-09-17 18:40
@fsoepyan I think this issue is similar to #131. To mimic the results you will need to use exactly same values for the 20 or 25 samples you're using on both OUU and Optimization tab.

**Comment by fsoepyan** [comment] 2018-10-02 17:58
Using the example Aspen Plus file from #131:
- I have 3 variables set as Z1, and 2 variables set as "Fixed"
- I ran OUU using the OUU tab
- After the OUU run is finished, I went to the "Flowsheet" table, and according to the "Flowsheet" table, the optimum solution occurs at:

Objective Value: -1724.61
conv: 0.95
H2_flow: 295.55
TOL_flow: 249.86

- This solution is different from what I got when I ran this problem using the "Optimization" tab:

Objective Value: -2280.04
conv: 0.95
H2_flow: 312.85
TOL_flow: 300.00

**Comment by sotorrio1** [comment] 2018-10-08 23:34
@fsoepyan please make sure you have same initial values for Z1 in both cases, OUU and Optimization, before running the optimization

**Comment by fsoepyan** [comment] 2018-10-09 17:29
Using the example Aspen Plus file from #131:
- I went to the Optimization tab
- I used the following values as the initial values of the decision variables:

conv: 0.75
H2_flow: 301
TOL_flow: 199

- The solution I got was:

Objective value: -2280.06
conv: 0.9500
H2_flow: 312.85
TOL_flow: 300.00

- I went to the OUU tab
- I set the above 3 variables as Z1, and the remaining 2 variables as "Fixed"
- I ran OUU
- After the OUU run is finished, the OUU table shows the following results:

Iteration: 59
Objective value: -111111
conv: 0.95
H2_flow: 223.983
TOL_flow: 247.243

- I went to the Flowsheet, and ran FOQUS using the above values of the variables
- I got an error message: "The simulation completed with an error 1, Failure in node calculation, check node status"
- I went to the Flowsheet table, and according to the Flowsheet table, the optimum solution occurs at:

Objective Value: -2280.06

- Good news: This value is the same as the one I got from the Optimization tab
- Bad news: According to the Flowsheet table, for all OUU iterations where the value of the objective is -2280.06, there is an error (i.e., the "err" column shows a value of 1)

- More bad news: These are the ranges that I got for the decision variables (Z1) according to the Flowsheet table:

conv: 0.60 to 0.95
H2_flow: 200.00 to 228.75
TOL_flow: 218.20 to 254.99

- These ranges are inconsistent with what I got when we ran this problem using the Optimization tab

**Comment by fsoepyan** [comment] 2018-10-09 17:51
I also tried out the Optimization and OUU tabs for the MEA example (ran with ALAMO):
- From the Optimization tab, the solution I got was:

Objective value: -215.58
X01: 11526.97
X02: 1000.0
X03: 0.1
X04: 0.1

- From the OUU tab table, the solution I got was:

Iteration: 67
Objective value: -172.1924
X01: 4547.794
X02: 1000.0
X03: 0.1
X04: 0.1

- This time, when I ran Flowsheet using the above values of X01 to X04, I got:

Objective value: -172.19220884837114

- Good news: This value is consistent with what is in the OUU table
- More good news: When I checked the Flowsheet table, the minimum values I got from running Optimization and OUU are consistent with the results generated by the Optimization and OUU tabs
- Bad news: The optimum solutions from the Optimization tab and OUU tab are different (-215.58 vs. -172.19)

**Comment by ksbeattie** [comment] 2018-10-09 20:15
@sotorrio1 will take a look at this.

**Comment by sotorrio1** [comment] 2018-10-16 00:31
@fsoepyan I tried two of your problems ("MEA_Column_02_15_2018.foqus" and "MEA_Column_06_13_2018.foqus"). I know they are basically the same problem but I wanted to double check the order of the variables wasn't affecting the results. Below the results of my experiments:

* "MEA_Column_02_15_2018.foqus"
    - Initial Values for Decision Variables (Z1) -- I chose the middle point within lower and upper bounds and I used these values for OUU, Optimization and Flowsheet tabs. 
        - X1 = 8,000
        - X2 = 2,000
        - X3 = 0.128
        - X4 = 0.225

    - X5 through X17 are fixed (same default values you have, I haven't modified those).

=========================================
OUU:
  - Objective = -215.5592
  - X1 = 11,526.97
  - X2 = 1,000
  - X3 = 0.1
  - X4 = 0.1

Optimization:
  - Objective = -215.55900
  - X1 = 11,526.97
  - X2 = 1,000
  - X3 = 0.1
  - X4 = 0.1

Flowsheet:
  - Objective = -215.559
=========================================

* "MEA_Column_06_13_2018.foqus"
    - Initial Values for Decision Variables (Z1) -- I chose the middle point within lower and upper bounds and I used these values for OUU, Optimization and Flowsheet tabs. 
        - X1 = 8,000
        - X2 = 2,000
        - X3 = 0.128
        - X4 = 0.225

    - X5 through X17 are fixed (same default values you have, I haven't modified those).

=========================================
OUU:
  - Objective = -215.581100
  - X1 = 11,526.97
  - X2 = 1,000
  - X3 = 0.1
  - X4 = 0.1

Optimization:
  - Objective = -215.5809
  - X1 = 11,526.97
  - X2 = 1,000
  - X3 = 0.1
  - X4 = 0.1

Flowsheet:
  - Objective = -215.58
=========================================

As you can see, the results are consistent across the 3 modules.

**Comment by fsoepyan** [comment] 2018-11-07 23:21
- I performed optimization using both the "Optimization" tab and the "OUU" tab
- Below is a summary of the results:

<img width="606" alt="ouu_11_07_2018" src="https://user-images.githubusercontent.com/30811140/48167453-bea34b80-e2b9-11e8-9881-b332d2c36458.png">

- 1st portion shows initial values of decision variables X01 to X04
- 2nd portion shows results from "Optimization" tab
- 3rd portion shows results from "OUU" tab

- Good news: the results from "OUU" tab and the "Flowsheet" run results are consistent
- Therefore, I will close Issue #131 

- Bad news: the results from "OUU" tab and "Optimization" tab are still inconsistent

**Comment by ksbeattie** [comment] 2019-01-15 21:06
@sotorrio1: in progress

**Comment by sotorrio1** [comment] 2019-02-06 18:17
This might be simply a matter of different optimizers. @eslickj What optimizer do you guys use in the Optimization module? We will check with Charles Tong about the one being used by psuade.

**Comment by fsoepyan** [comment] 2019-02-06 18:23
The optimizer we usually use is BOBYQA.

**Comment by ksbeattie** [comment] 2019-04-09 20:04
@fsoepyan will try to reproduce the original issue, so that @sotorrio1 can get a clearer picture on what might be the fix.

**Comment by fsoepyan** [comment] 2019-04-12 16:40
When I ran OUU for the MEA example, the message box that usually appears did not appear, the results were not generated, and according to the Anaconda prompt:

![image](https://user-images.githubusercontent.com/30811140/56052696-1c800780-5d20-11e9-9d76-77075c35f8a2.png)

**Comment by ksbeattie** [comment] 2019-04-16 19:45
@sotorrio1 is working on this.

**Comment by sotorrio1** [comment] 2019-04-24 00:15
@fsoepyan when you run OUU and get this error, are you selecting a specific node or the whole Flowsheet? Thanks!

**Comment by fsoepyan** [comment] 2019-04-24 17:59
If I remember correctly, I selected the whole Flowsheet.

**Comment by ksbeattie** [comment] 2019-04-30 20:06
@sotorrio1 is working with @fsoepyan on reproducing this.

**Comment by sotorrio1** [comment] 2019-05-02 00:04
OUU should work after PR #479 is merged. Then we can focus on the different solutions generated by OUU and the Optimization tab.

**Comment by fsoepyan** [comment] 2019-05-06 15:17
- I tested the Optimization and OUU tabs using the MEA example that uses an ALAMO surrogate model
- I made sure that the bounds of the decision variables (X1 to X4) are the same for both cases
- I also made sure that the initial values of the decision variables, and the values of the constant (i.e., fixed) variables are the same for both cases
- I used BOBYQA for both the Optimization and OUU tabs
- When I ran optimization using the Optimization tab, the optimum value of the objective I got was: -215.58
- When I ran optimization using the OUU tab (I have only Z1 and Fixed variables), the optimum value of the objective I got was: -179.59
- For the decision variables, at the solution, the value of X1 are different

**Comment by sotorrio1** [comment] 2019-05-06 19:39
@fsoepyan I was able to reproduce your results. I think this might be a matter of the random seed. In OUU we have the random seed hard-coded to 41491431, while I think in the Optimization tab (where you are using NLopt the seed is randomize using the system time (https://nlopt.readthedocs.io/en/latest/NLopt_Python_Reference/)

**Comment by sotorrio1** [comment] 2019-05-06 20:44
@fsoepyan I was able to reproduce your results. As of now I'm not entirely sure why the solutions are different, but it might have something to do with the random seed.

**Comment by ksbeattie** [comment] 2019-05-21 20:21
@sotorrio1 is reaching out to Charles on how psuade uses the random seed and if that is the culprit or if the use of that seed could be removed (or could be set so results can be reproduced).

**Comment by sotorrio1** [comment] 2019-05-22 22:49
According to Charles, the random seed may affect the solution of the optimization because OUU involves creating many random samples. So, if the user desires repeatability, always use a fixed random seed. 

Right now we're using a fixed random seed when running OUU so we can always get the same solution when running same problem. If we want to get the same solution when comparing OUU with the Optimization tab, we need to use the same fixed random seed in the optimization tab. 

@fsoepyan and/or @eslickj do you have any idea what's the case for the optimization tab?

**Comment by eslickj** [comment] 2019-05-23 16:57
@fsoepyan can double check but I think the random seed may be a setting.  The BOBYQA in the optimization tab doesn't come from PSUADE it comes form NLopt, so it wouldn't be surprizing if the results were a little different.

**Comment by sotorrio1** [comment] 2019-05-23 17:32
Exactly, what I've read is that BOBYQA by default uses the system's time (of course transformed as an integer) as the random seed. My understanding on this is that unless we can fix both random seeds to the same value, we won't get the exact same results.

**Closed** 2019-05-28 20:10 UTC
Labels: OUU
